In [2]:
import pandas as pd
from sklearn import *
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
import numpy as np


In [7]:
df = pd.DataFrame({"x1":[[1,2,3] for i in range(4)], 
                  "x2":[1.2,1.332,11.2,1.],
                  "x3":['aaa', 'bb', 'a', 'c']})

In [8]:
preprocessing.OneHotEncoder(categories=df.x3)

OneHotEncoder(categories=0    aaa
1     bb
2      a
3      c
Name: x3, dtype: object)

In [9]:
encoder = preprocessing.OneHotEncoder()
sub = encoder.fit_transform(df.x3.to_numpy().reshape(-1,1))
df2 = pd.DataFrame(sub.toarray(), columns = encoder.get_feature_names_out())

In [10]:
pd.concat([df,df2], axis=1)

x1      x2   x3  x0_a  x0_aaa  x0_bb  x0_c
0  [1, 2, 3]   1.200  aaa   0.0     1.0    0.0   0.0
1  [1, 2, 3]   1.332   bb   0.0     0.0    1.0   0.0
2  [1, 2, 3]  11.200    a   1.0     0.0    0.0   0.0
3  [1, 2, 3]   1.000    c   0.0     0.0    0.0   1.0

In [11]:
encoder = preprocessing.LabelEncoder()
sub = encoder.fit_transform(df.x3.to_numpy().reshape(-1,1))
df['labeled_x3'] = sub
df

C:\Users\tereh\Desktop\some\programmin\systems_prog\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


x1      x2   x3  labeled_x3
0  [1, 2, 3]   1.200  aaa           1
1  [1, 2, 3]   1.332   bb           2
2  [1, 2, 3]  11.200    a           0
3  [1, 2, 3]   1.000    c           3

In [3]:
import tensorflow as tf
import torch
import numpy as np
import pandas as pd

In [4]:
df = pd.DataFrame({
    'x1': [1,2,3,4],
    'x2': [2,3,3,4],
    'x3': [3,2,3,1],
    'x4': [5,2,1,2]
      })
df2 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [6, 7, 8, 9, 10],
    'C': [11, 12, 13, 14, 15]
})

In [5]:
tensor_tf = tf.convert_to_tensor(df.values)
tensor_torch = torch.tensor(df.values)
tensor_numpy = df.values

In [6]:
print(tensor_tf)
print(tensor_torch)
print(tensor_numpy)

tf.Tensor(
[[1 2 3 5]
 [2 3 2 2]
 [3 3 3 1]
 [4 4 1 2]], shape=(4, 4), dtype=int64)
tensor([[1, 2, 3, 5],
        [2, 3, 2, 2],
        [3, 3, 3, 1],
        [4, 4, 1, 2]])
[[1 2 3 5]
 [2 3 2 2]
 [3 3 3 1]
 [4 4 1 2]]
